
//This file should be called cbmc_main_acbd_manager.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_acbd_manager.c F_acbd_manager.c


#include "F_acbd_manager.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for acbd_manager
	enforcervars_acbd_manager_t enf_acbd_manager;
    inputs_acbd_manager_t inputs_acbd_manager;
    outputs_acbd_manager_t outputs_acbd_manager;

	//set values to known state
    acbd_manager_init_all_vars(&enf_acbd_manager, &inputs_acbd_manager, &outputs_acbd_manager);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	enf_acbd_manager.v = nondet_acbd_manager_enf_am_0();
	
	enf_acbd_manager._policy_am_state = nondet_acbd_manager_enf_am_state() % 2;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	acbd_manager_run_via_enforcer(&enf_acbd_manager, &inputs_acbd_manager, &outputs_acbd_manager);

}


void acbd_manager_run(inputs_acbd_manager_t *inputs, outputs_acbd_manager_t *outputs) {
    //randomise controller

    outputs->activate_ab = nondet_acbd_manager_output_0();
	outputs->activate_cd = nondet_acbd_manager_output_1();
	 
}

